# additionalTrustBundlePolicy: Proxyonly 
apiVersion: v1
Kind: InstallConfig
metadata:
  creationTimestamp: null
  name: steven-workload-testing
sshKey: "${WI_SSH_KEY_PUBLIC}"
publish: "Internal"
fips: true
baseDomain: catchall.azure.devcluster.openshift.com
featureSet: TechPreviewNoUpgrade
pullSecret: '${PULL_SECRET}'
credentialsMode: Manual
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 3
  platform:
    azure:
      type: Standard_D4s_V3
      zones: ["1", "2", "3"]
      vmNetworkingType: Accelerated
controlPlane:
  architecture: amd64
  hyperthreading: Enabled 
  name: master
  replicas: 3
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  azure:
    region: eastus
    networkResourceGroupName: ${RESOURCEGROUP_NETWORK}
    computeSubnet: ${WORKER_SUBNET}
    controlPlaneSubnet: ${MASTER_SUBNET}
    virtualNetwork: ${VNET}
    cloudName: AzurePublicCloud
    resourceGroupName: ${RESOURCEGROUP_CLUSTER}
